### PR TITLE
Reimplement as a Go Binary

### LINKED ISSUE #12: Reimplement as a Go binary
An idea that @rgbkrk and I have been tossing around.

## Pros

 * Single-binary, zero-dependency binary that's easy to install.
 * Can use real JSON and https libraries to implement things like `ls-remote` robustly without needing to resort to ugly curl and sed pipelines.
 * No need to worry about preserving cross-shell compatibility.

## Cons

 * `dvm use` can't be done directly because we aren't sourced into the shell; we'll need to do `eval` hacks like `docker-machine env` uses.
 * Can't leverage `nvm` source as a reference.
 * It means rewriting all of our existing work.

### PR DESCRIPTION
**Pull request by carolynvs**
- [x] help
- [x] version
- [x] install
- [x] use
- [x] use system
- [x] list-remote
- [x] uninstall
- [x] current
- [x] ls
- [x] deactivate
- [x] alias
- [x] unalias
- [ ] ~~unload~~ Since we aren't polluting the shell session with lots of functions with the go binary, this doesn't seem necessary. The only function exposed is `dvm` itself.
- [x] which
- [x] experimental version support
- [x] Carina support

    ```bash
    ~/Downloads/mccluster$ source ~/.dvm/dvm.sh
    ~/Downloads/mccluster$ source docker.env
    ~/Downloads/mccluster$ dvm use
    Now using Docker 1.8.3
    ```
___

I have dvm script wrappers working on all 3 shells. Each wrapper script:

1. Copies the dvm-helper go binary from the bin into the DVM_DIR, if not present. Eventually this will download the latest release.
2. Removes any previous dvm-output script.
3. Runs dvm-helper passing all arguments.
4. Runs dvm-output, if present.

**Bash**

```bash
$ docker -v
Docker version 1.8.1, build d12ea79

$ source ~/src/dvm/dvm.sh

$ dvm help
NAME:
   Docker Version Manager - Manage multiple versions of the Docker client

USAGE:
   /Users/caro8994/src/dvm/dvm [global options] command [command options] [arguments...]

VERSION:
   0.0.0

COMMANDS:
   install, i	Download and install a <version>. Uses $DOCKER_VERSION if available
   use		Modify PATH to use <version>. Uses $DOCKER_VERSION if available
   help, h	Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --dvm-dir 			Specify an alternate DVM home directory, defaults to the current directory. [$DVM_DIR]
   --shell 			Specify the shell format in which environment variables should be output, e.g. powershell, cmd or sh/bash. Defaults to sh/bash. [$SHELL]
   --debug			Print additional debug information.
   --silent			Suppress output. Errors will still be displayed. [$DVM_SILENT]
   --help, -h			show help
   --generate-bash-completion
   --version, -v		print the version

$ dvm install 1.8.2
Installing 1.8.2

$ docker -v
Docker version 1.8.1, build d12ea79

$ dvm use 1.8.2
Now using Docker 1.8.2

$ docker -v
Docker version 1.8.2, build 0a8c2e3

$ dvm use 1.8.3
1.8.3 is not installed. Installing now...
Installing 1.8.3
Now using Docker 1.8.3

$ docker -v
Docker version 1.8.3, build f4bf5c7
```

**PowerShell**

```powershell
> docker -v
Docker version 1.8.1, build d12ea79

> . Y:\src\dvm\dvm.ps1

> dvm help
NAME:
   Docker Version Manager - Manage multiple versions of the Docker client

USAGE:
   Y:\src\dvm\dvm.exe [global options] command [command options] [arguments...]

VERSION:
   0.0.0

COMMANDS:
   install, i   Download and install a <version>. Uses $DOCKER_VERSION if available
   use          Modify PATH to use <version>. Uses $DOCKER_VERSION if available
   help, h      Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --dvm-dir                    Specify an alternate DVM home directory, defaults to the current directory. [$DVM_DIR]
   --shell                      Specify the shell format in which environment variables should be output, e.g. powershell, cmd or sh/bash. Defaults to sh/bash. [$SHELL]
   --debug                      Print additional debug information.
   --silent                     Suppress output. Errors will still be displayed. [$DVM_SILENT]
   --help, -h                   show help
   --generate-bash-completion
   --version, -v                print the version

> dvm install 1.8.2
Installing 1.8.2

> docker -v
Docker version 1.8.1, build d12ea79

> dvm use 1.8.2
Now using Docker 1.8.2

> docker -v
Docker version 1.8.2, build 0a8c2e3

> dvm use 1.8.3
1.8.3 is not installed. Installing now...
Installing 1.8.3
Now using Docker 1.8.3

> docker -v
Docker version 1.8.3, build f4bf5c7
```

**CMD**

```batch
>docker -v
Docker version 1.8.1, build d12ea79

>PATH=Y:\src\dvm;%PATH%

>dvm help
NAME:
   Docker Version Manager - Manage multiple versions of the Docker client

USAGE:
   Y:\src\dvm\\dvm-helper.exe [global options] command [command options] [arguments...]

VERSION:
   0.0.0

COMMANDS:
   install, i   Download and install a <version>. Uses $DOCKER_VERSION if available
   use          Modify PATH to use <version>. Uses $DOCKER_VERSION if available
   help, h      Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --dvm-dir                    Specify an alternate DVM home directory, defaults to the current directory. [$DVM_DIR]
   --shell                      Specify the shell format in which environment variables should be output, e.g. powershell, cmd or sh/bash. Defaults to sh/bash. [$SHELL]
   --debug                      Print additional debug information.
   --silent                     Suppress output. Errors will still be displayed. [$DVM_SILENT]
   --help, -h                   show help
   --generate-bash-completion
   --version, -v                print the version


>dvm install 1.8.2
Installing 1.8.2

>docker -v
Docker version 1.8.1, build d12ea79

>dvm use 1.8.2
Now using Docker 1.8.2

>docker -v
Docker version 1.8.2, build 0a8c2e3

>dvm use 1.8.3
1.8.3 is not installed. Installing now...
Installing 1.8.3
Now using Docker 1.8.3

>docker -v
Docker version 1.8.3, build f4bf5c7

```

Fixes #12

### CODE REVIEW

**Comment by carolynvs** [comment]
cc @smashwilson @rgbkrk I'm going to keep chugging along and update this PR as I go. Let me know if you see any problems, never used go before. :smile:

**Comment by carolynvs** [comment]
I believe I've gotten all the important bits and will make issues for the leftovers:

* bash completion
* support bash on Windows

**Comment by rgbkrk** [comment]
Well now. Well done.

**Comment by rgbkrk** [comment]
Thanks for doing this and sorry I never came back to it. I'll make some follow on PRs and post issues as I use it.

**Pull request merged**
