### PR TITLE
[WIP]Use godeps to vendor dependencies

### LINKED ISSUE #122: Pin Dependencies
The build just failed because of breaking changes in a dependency: https://travis-ci.org/getcarina/dvm/builds/139880399.

```bash
# github.com/getcarina/dvm/dvm-helper

dvm-helper/dvm-helper.go:699: cannot use releases (type []*github.RepositoryRelease) as type []github.RepositoryRelease in append

make: *** [get-deps] Error 2
```

We should pin to a known good version or something similar so that builds don't break unexpectedly.

### PR DESCRIPTION
**Pull request by carolynvs**
This uses the latest version of godeps (v74) to take advantage of the vendor support in golang 1.6.

Closes #122

### CODE REVIEW

**Comment by rgbkrk** [comment]
Are folks still against including only Godeps.json and not all the dependencies?

**Comment by carolynvs** [comment]
I'm not sure who these folks are? _looks around suspiciously_

I went down this path because it is the recommended/documented way from both the go developers and godeps. Is there a way to use godeps but not check in the vendor directory?

**Comment by carolynvs** [comment]
Just to clarify, I don't want to check in `/vendor` either but couldn't figure out how to do so and just settled for this. 😄

**Comment by carolynvs** [comment]
I'm going to try out glide instead and if it looks good, submit in a separate PR. Seems a lot closer to what I want to do.

**Pull request closed without merging**
